version: '2'

services:
  site:
    image: jekyll/builder
    command: jekyll serve
    volumes:
      - ./:/srv/jekyll
    ports:
      -  4000:4000
      - 35729:35729
      -  3000:3000
      -    80:4000
